// Code generated by MockGen. DO NOT EDIT.
// Source: foo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFoo is a mock of Foo interface.
type MockFoo struct {
	ctrl     *gomock.Controller
	recorder *MockFooMockRecorder
}

// MockFooMockRecorder is the mock recorder for MockFoo.
type MockFooMockRecorder struct {
	mock *MockFoo
}

// NewMockFoo creates a new mock instance.
func NewMockFoo(ctrl *gomock.Controller) *MockFoo {
	mock := &MockFoo{ctrl: ctrl}
	mock.recorder = &MockFooMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFoo) EXPECT() *MockFooMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockFoo) Do(arg0 int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", arg0)
	ret0, _ := ret[0].(int)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MockFooMockRecorder) Do(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockFoo)(nil).Do), arg0)
}

// MockFoo2 is a mock of Foo2 interface.
type MockFoo2 struct {
	ctrl     *gomock.Controller
	recorder *MockFoo2MockRecorder
}

// MockFoo2MockRecorder is the mock recorder for MockFoo2.
type MockFoo2MockRecorder struct {
	mock *MockFoo2
}

// NewMockFoo2 creates a new mock instance.
func NewMockFoo2(ctrl *gomock.Controller) *MockFoo2 {
	mock := &MockFoo2{ctrl: ctrl}
	mock.recorder = &MockFoo2MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFoo2) EXPECT() *MockFoo2MockRecorder {
	return m.recorder
}

// Do2 mocks base method.
func (m *MockFoo2) Do2(arg0 int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do2", arg0)
	ret0, _ := ret[0].(int)
	return ret0
}

// Do2 indicates an expected call of Do2.
func (mr *MockFoo2MockRecorder) Do2(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do2", reflect.TypeOf((*MockFoo2)(nil).Do2), arg0)
}
